'use strict';

// automation:
//  'auto'    -> converted directly by this tool (assets/data copy + transform)
//  'partial' -> scaffold/stub generated, logic must be finished in Java
//  'manual'  -> only documented + logged; Bedrock concept has no Java mod equivalent
//               (or depends on Bedrock's JS Scripting API, which has no Java mod equivalent)

const FEATURES = [
  // --- Content definitions (auto: JSON-driven) ---
  { name: 'Blocks', category: 'blocks', automation: 'auto' },
  { name: 'Custom Blocks', category: 'blocks', automation: 'auto' },
  { name: 'Custom Items', category: 'items', automation: 'auto' },
  { name: 'Custom Tools', category: 'items', automation: 'auto' },
  { name: 'Custom Weapons', category: 'items', automation: 'auto' },
  { name: 'Custom Armor', category: 'items', automation: 'auto' },
  { name: 'Custom Food', category: 'items', automation: 'auto' },
  { name: 'Custom Consumables', category: 'items', automation: 'auto' },

  // --- Entities (partial: data converts, behavior logic needs Java) ---
  { name: 'Custom Mobs', category: 'entities', automation: 'partial' },
  { name: 'Custom Animals', category: 'entities', automation: 'partial' },
  { name: 'Custom Monsters', category: 'entities', automation: 'partial' },
  { name: 'Custom NPCs', category: 'entities', automation: 'partial' },
  { name: 'Custom Bosses', category: 'entities', automation: 'partial' },
  { name: 'Custom Projectiles', category: 'entities', automation: 'partial' },
  { name: 'Custom Vehicles', category: 'entities', automation: 'partial' },
  { name: 'Custom Entities', category: 'entities', automation: 'partial' },

  // --- Recipes / loot (auto-ish: structural JSON translation) ---
  { name: 'Crafting Recipes', category: 'recipes', automation: 'auto' },
  { name: 'Furnace Recipes', category: 'recipes', automation: 'auto' },
  { name: 'Smithing Recipes', category: 'recipes', automation: 'auto' },
  { name: 'Stonecutter Recipes', category: 'recipes', automation: 'auto' },
  { name: 'Brewing Recipes', category: 'recipes', automation: 'partial' },
  { name: 'Loot Tables', category: 'loot_tables', automation: 'auto' },
  { name: 'Trade Tables', category: 'trading', automation: 'partial' },
  { name: 'Custom Drops', category: 'loot_tables', automation: 'auto' },

  // --- World generation (partial: Java worldgen is datapack/code, very different) ---
  { name: 'World Generation', category: 'worldgen', automation: 'partial' },
  { name: 'Custom Structures', category: 'worldgen', automation: 'partial' },
  { name: 'Custom Features', category: 'worldgen', automation: 'partial' },
  { name: 'Custom Trees', category: 'worldgen', automation: 'partial' },
  { name: 'Custom Ores', category: 'worldgen', automation: 'partial' },
  { name: 'Custom Plants', category: 'worldgen', automation: 'partial' },
  { name: 'Custom Biomes (limited)', category: 'worldgen', automation: 'manual' },
  { name: 'Dimension Features (limited)', category: 'worldgen', automation: 'manual' },

  // --- AI / behavior (manual: components.json -> Java Goal classes, no auto map) ---
  { name: 'Entity AI', category: 'entity_ai', automation: 'manual' },
  { name: 'Custom Behaviors', category: 'entity_ai', automation: 'manual' },
  { name: 'Attack Patterns', category: 'entity_ai', automation: 'manual' },
  { name: 'Movement Behaviors', category: 'entity_ai', automation: 'manual' },
  { name: 'Pathfinding', category: 'entity_ai', automation: 'manual' },

  // --- Animation / VFX ---
  { name: 'Animations', category: 'animations', automation: 'partial' },
  { name: 'Animation Controllers', category: 'animations', automation: 'manual' },
  { name: 'Particles', category: 'particles', automation: 'partial' },
  { name: 'Custom Particle Effects', category: 'particles', automation: 'partial' },
  { name: 'Visual Effects', category: 'particles', automation: 'manual' },
  { name: 'Screen Effects', category: 'particles', automation: 'manual' },

  // --- Assets (auto: direct file copy/repack) ---
  { name: 'Textures', category: 'textures', automation: 'auto' },
  { name: 'Block Textures', category: 'textures', automation: 'auto' },
  { name: 'Item Textures', category: 'textures', automation: 'auto' },
  { name: 'Entity Textures', category: 'textures', automation: 'auto' },
  { name: 'GUI Textures', category: 'textures', automation: 'auto' },
  { name: 'Sky Textures', category: 'textures', automation: 'auto' },
  { name: 'Environment Textures', category: 'textures', automation: 'auto' },
  { name: 'Models', category: 'models', automation: 'partial' },
  { name: 'Block Models', category: 'models', automation: 'partial' },
  { name: 'Item Models', category: 'models', automation: 'partial' },
  { name: 'Entity Geometry', category: 'models', automation: 'partial' },
  { name: 'Sounds', category: 'sounds', automation: 'auto' },
  { name: 'Music', category: 'sounds', automation: 'auto' },
  { name: 'Ambient Sounds', category: 'sounds', automation: 'auto' },
  { name: 'Mob Sounds', category: 'sounds', automation: 'auto' },
  { name: 'Block Sounds', category: 'sounds', automation: 'auto' },
  { name: 'Item Sounds', category: 'sounds', automation: 'auto' },
  { name: 'Localization', category: 'lang', automation: 'auto' },
  { name: 'Custom Languages', category: 'lang', automation: 'auto' },
  { name: 'Translations', category: 'lang', automation: 'auto' },

  // --- Logic layer (manual: Bedrock JS Scripting API has no Java equivalent) ---
  { name: 'Commands', category: 'commands', automation: 'partial' },
  { name: 'Custom Functions', category: 'commands', automation: 'partial' },
  { name: 'Command Integration', category: 'commands', automation: 'manual' },
  { name: 'Scoreboard Systems', category: 'commands', automation: 'manual' },
  { name: 'Tag Systems', category: 'commands', automation: 'manual' },
  { name: 'Scripting API', category: 'scripting', automation: 'manual' },
  { name: 'JavaScript Logic', category: 'scripting', automation: 'manual' },
  { name: 'Custom Events', category: 'scripting', automation: 'manual' },
  { name: 'Timers', category: 'scripting', automation: 'manual' },
  { name: 'Scheduled Tasks', category: 'scripting', automation: 'manual' },
  { name: 'Dynamic Properties', category: 'scripting', automation: 'manual' },
  { name: 'Data Storage', category: 'scripting', automation: 'manual' },
  { name: 'World Events', category: 'scripting', automation: 'manual' },
  { name: 'Player Events', category: 'scripting', automation: 'manual' },
  { name: 'Block Events', category: 'scripting', automation: 'manual' },
  { name: 'Entity Events', category: 'scripting', automation: 'manual' },

  // --- High-level gameplay systems (manual: game-design layer, not file-based) ---
  { name: 'Gameplay Mechanics', category: 'gameplay', automation: 'manual' },
  { name: 'Skills', category: 'gameplay', automation: 'manual' },
  { name: 'Classes', category: 'gameplay', automation: 'manual' },
  { name: 'Abilities', category: 'gameplay', automation: 'manual' },
  { name: 'Magic Systems', category: 'gameplay', automation: 'manual' },
  { name: 'Leveling', category: 'gameplay', automation: 'manual' },
  { name: 'Experience Systems', category: 'gameplay', automation: 'manual' },
  { name: 'Quest Systems', category: 'gameplay', automation: 'manual' },
  { name: 'Economy Systems', category: 'gameplay', automation: 'manual' },
  { name: 'Currency', category: 'gameplay', automation: 'manual' },
  { name: 'Shops', category: 'gameplay', automation: 'manual' },
  { name: 'Banking', category: 'gameplay', automation: 'manual' },
  { name: 'Jobs', category: 'gameplay', automation: 'manual' },
  { name: 'Professions', category: 'gameplay', automation: 'manual' },
  { name: 'Survival Features', category: 'gameplay', automation: 'manual' },
  { name: 'Temperature', category: 'gameplay', automation: 'manual' },
  { name: 'Thirst', category: 'gameplay', automation: 'manual' },
  { name: 'Hunger Expansion', category: 'gameplay', automation: 'manual' },
  { name: 'Stamina', category: 'gameplay', automation: 'manual' },
  { name: 'Radiation', category: 'gameplay', automation: 'manual' },
  { name: 'Diseases', category: 'gameplay', automation: 'manual' },
  { name: 'Sanity', category: 'gameplay', automation: 'manual' },
  { name: 'Technology', category: 'gameplay', automation: 'manual' },
  { name: 'Machines', category: 'gameplay', automation: 'manual' },
  { name: 'Generators', category: 'gameplay', automation: 'manual' },
  { name: 'Electricity Systems', category: 'gameplay', automation: 'manual' },
  { name: 'Automation', category: 'gameplay', automation: 'manual' },
  { name: 'Pipes', category: 'gameplay', automation: 'manual' },
  { name: 'Conveyors', category: 'gameplay', automation: 'manual' },
  { name: 'Farming', category: 'gameplay', automation: 'partial' },
  { name: 'New Crops', category: 'gameplay', automation: 'partial' },
  { name: 'Fruit Trees', category: 'gameplay', automation: 'partial' },
  { name: 'Fishing Systems', category: 'gameplay', automation: 'manual' },
  { name: 'Animal Breeding', category: 'gameplay', automation: 'manual' },
  { name: 'Beekeeping', category: 'gameplay', automation: 'manual' },
  { name: 'Combat', category: 'gameplay', automation: 'manual' },
  { name: 'New Enchantments', category: 'gameplay', automation: 'partial' },
  { name: 'Status Effects', category: 'gameplay', automation: 'partial' },
  { name: 'Custom Damage Types', category: 'gameplay', automation: 'partial' },
  { name: 'Critical Systems', category: 'gameplay', automation: 'manual' },
  { name: 'Ranged Weapons', category: 'gameplay', automation: 'partial' },
  { name: 'Explosives', category: 'gameplay', automation: 'partial' },
  { name: 'Building', category: 'blocks', automation: 'auto' },
  { name: 'Furniture', category: 'blocks', automation: 'partial' },
  { name: 'Decoration Blocks', category: 'blocks', automation: 'auto' },
  { name: 'Lighting', category: 'blocks', automation: 'auto' },
  { name: 'Doors', category: 'blocks', automation: 'partial' },
  { name: 'Windows', category: 'blocks', automation: 'auto' },
  { name: 'Roofs', category: 'blocks', automation: 'auto' },
  { name: 'Building Tools', category: 'items', automation: 'partial' },
  { name: 'Exploration', category: 'worldgen', automation: 'manual' },
  { name: 'Dungeons', category: 'worldgen', automation: 'partial' },
  { name: 'Ruins', category: 'worldgen', automation: 'partial' },
  { name: 'Villages', category: 'worldgen', automation: 'manual' },
  { name: 'Castles', category: 'worldgen', automation: 'partial' },
  { name: 'Dimensions Support', category: 'worldgen', automation: 'manual' },
  { name: 'Treasure Systems', category: 'loot_tables', automation: 'auto' },
  { name: 'Multiplayer', category: 'gameplay', automation: 'manual' },
  { name: 'Custom Minigames', category: 'gameplay', automation: 'manual' },
  { name: 'PvP Systems', category: 'gameplay', automation: 'manual' },
  { name: 'Teams', category: 'gameplay', automation: 'manual' },
  { name: 'Guilds', category: 'gameplay', automation: 'manual' },
  { name: 'Leaderboards', category: 'gameplay', automation: 'manual' },
  { name: 'UI', category: 'ui', automation: 'manual' },
  { name: 'Action Bar Messages', category: 'ui', automation: 'manual' },
  { name: 'Titles', category: 'ui', automation: 'manual' },
  { name: 'Boss Bars', category: 'ui', automation: 'manual' },
  { name: 'Forms API', category: 'ui', automation: 'manual' },
  { name: 'Buttons', category: 'ui', automation: 'manual' },
  { name: 'Menus', category: 'ui', automation: 'manual' },
  { name: 'Dialogs', category: 'ui', automation: 'manual' },
  { name: 'Player', category: 'player', automation: 'manual' },
  { name: 'Custom Spawn Rules', category: 'entities', automation: 'partial' },
  { name: 'Custom Attributes', category: 'entities', automation: 'partial' },
  { name: 'Movement Abilities', category: 'player', automation: 'manual' },
  { name: 'Flying', category: 'player', automation: 'manual' },
  { name: 'Double Jump', category: 'player', automation: 'manual' },
  { name: 'Dash', category: 'player', automation: 'manual' },
  { name: 'Wall Climb', category: 'player', automation: 'manual' },
  { name: 'Weather', category: 'worldgen', automation: 'manual' },
  { name: 'Custom Weather Logic', category: 'worldgen', automation: 'manual' },
  { name: 'Season Systems', category: 'worldgen', automation: 'manual' },
  { name: 'Storm Events', category: 'worldgen', automation: 'manual' },
  { name: 'Pets', category: 'entities', automation: 'partial' },
  { name: 'Tamable Creatures', category: 'entities', automation: 'partial' },
  { name: 'Companions', category: 'entities', automation: 'manual' },
  { name: 'Mounts', category: 'entities', automation: 'partial' },
  { name: 'Security', category: 'gameplay', automation: 'manual' },
  { name: 'Claim Systems', category: 'gameplay', automation: 'manual' },
  { name: 'Lock Systems', category: 'gameplay', automation: 'manual' },
  { name: 'Permissions', category: 'gameplay', automation: 'manual' },
  { name: 'Utilities', category: 'items', automation: 'partial' },
  { name: 'Backpacks', category: 'items', automation: 'manual' },
  { name: 'Portable Storage', category: 'items', automation: 'manual' },
  { name: 'Waypoints', category: 'gameplay', automation: 'manual' },
  { name: 'Teleport Systems', category: 'gameplay', automation: 'manual' },
  { name: 'Gravestones', category: 'gameplay', automation: 'manual' },
  { name: 'Home System', category: 'gameplay', automation: 'manual' },
  { name: 'Achievements', category: 'advancements', automation: 'partial' },
  { name: 'Advancements', category: 'advancements', automation: 'partial' },
  { name: 'Challenges', category: 'advancements', automation: 'manual' },
  { name: 'Daily Rewards', category: 'gameplay', automation: 'manual' },
  { name: 'Progression Systems', category: 'gameplay', automation: 'manual' }
];

// Unique technical categories that the conversion engine actually walks the filesystem for.
const CATEGORY_ORDER = [
  'textures', 'sounds', 'lang', 'models', 'blocks', 'items',
  'recipes', 'loot_tables', 'trading', 'entities', 'entity_ai',
  'animations', 'particles', 'commands', 'worldgen', 'advancements',
  'scripting', 'gameplay', 'ui', 'player'
];

function categoriesFromSelection(selectedFeatureNames) {
  const set = new Set();
  for (const f of FEATURES) {
    if (selectedFeatureNames.includes(f.name)) set.add(f.category);
  }
  return CATEGORY_ORDER.filter((c) => set.has(c));
}

module.exports = { FEATURES, CATEGORY_ORDER, categoriesFromSelection };
